apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-8z8l
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0061-tenant/tkrw-pr712-0075-0061-app/devfile-sample-8z8l@sha256:ce0702f79929f9135833bc2c63ee91cfbf18198228af28808e162e9e62b6f958
        name: my-nodejs
        resources: {}
status: {}
